name: run-tests

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                laravel: [13.*, 12.*]
                php: ['8.5', '8.4', '8.3', '8.2']
                exclude:
                    - laravel: 13.*
                      php: '8.2'

        name: L${{ matrix.laravel }} - PHP${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Install SQLite 3
                run: |
                    sudo apt-get update
                    sudo apt-get install sqlite3
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: mbstring, pdo, sqlite, pdo_sqlite, iconv
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "illuminate/database:${{ matrix.laravel }}" --no-interaction --no-update
                    composer update --no-interaction
            -   name: Execute tests
                run: |
                    echo "Laravel ${{  matrix.laravel }}"
                    php -v | head -1
                    ./vendor/bin/phpunit
